-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 18:15:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scu-marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scu-marketplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scu-marketplace` DEFAULT CHARACTER SET utf8 ;
USE `scu-marketplace` ;

-- -----------------------------------------------------
-- Table `scu-marketplace`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scu-marketplace`.`user` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `is_seller` BIT(1) NULL DEFAULT 0,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `scu-marketplace`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scu-marketplace`.`products` (
  `product_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `photo` TEXT NULL DEFAULT NULL,
  `is_sold` SMALLINT NULL DEFAULT 0,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scu-marketplace`.`user_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scu-marketplace`.`user_products` (
  `email` VARCHAR(255) NOT NULL,
  `product_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`, `product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
